/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2COt3Kwbokt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export default function LearningMaterialV1() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <img
            src="/placeholder.svg"
            width={40}
            height={40}
            alt="English Learning Center"
            style={{ aspectRatio: "40/40", objectFit: "cover" }}
          />
          <h1 className="text-2xl font-bold">English Learning Center</h1>
        </div>
       
      </header>
      <div className="flex-1 flex">
        <nav className="bg-background border-r w-64 p-6 space-y-4">
          <h2 className="text-lg font-bold">Lessons</h2>
          <ul className="space-y-2">
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Beginner English
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Intermediate English
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Advanced English
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Business English
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                English for Travelers
              </Link>
            </li>
          </ul>
          <h2 className="text-lg font-bold">Resources</h2>
          <ul className="space-y-2">
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Grammar Guides
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Vocabulary Lists
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Pronunciation Tips
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="block rounded-md px-3 py-2 hover:bg-muted hover:text-muted-foreground"
                prefetch={false}
              >
                Conversation Practice
              </Link>
            </li>
          </ul>
        </nav>
        <main className="flex-1 p-8">
          <div className="prose max-w-3xl">
            <h1>Introduction to English Grammar</h1>
            <p>
              Welcome to our comprehensive guide on English grammar. In this lesson, we'll cover the fundamental
              concepts and structures that form the backbone of the English language. Whether you're a beginner or
              looking to refresh your knowledge, this guide will provide you with a solid foundation to improve your
              communication skills.
            </p>
            <h2>Parts of Speech</h2>
            <p>
              The English language is composed of different parts of speech, each with its own function and
              characteristics. These include:
            </p>
            <ul>
              <li>Nouns: Words that represent people, places, things, or ideas.</li>
              <li>Verbs: Words that describe actions, states of being, or occurrences.</li>
              <li>Adjectives: Words that modify or describe nouns and pronouns.</li>
              <li>Adverbs: Words that modify verbs, adjectives, or other adverbs.</li>
              <li>Pronouns: Words that substitute for nouns to avoid repetition.</li>
              <li>
                Prepositions: Words that show the relationship between a noun or pronoun and other parts of the
                sentence.
              </li>
              <li>Conjunctions: Words that connect words, phrases, or clauses together.</li>
              <li>Interjections: Words that express emotion or surprise.</li>
            </ul>
            <h2>Sentence Structure</h2>
            <p>
              The basic structure of an English sentence consists of a subject, a verb, and an object (if applicable).
              The subject is the noun or pronoun that performs the action, the verb is the action being taken, and the
              object is the noun or pronoun that receives the action.
            </p>
            <img
              src="/placeholder.svg"
              width={600}
              height={300}
              alt="Sentence structure diagram"
              className="mx-auto"
              style={{ aspectRatio: "600/300", objectFit: "cover" }}
            />
            <p>
              Understanding these fundamental parts of speech and sentence structure will provide you with a solid
              foundation to build upon as you continue to improve your English skills.
            </p>
          </div>
        </main>
      </div>
    </div>
  )
}
