/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QGoZuFqGEjW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/drake_libs/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/drake_libs/ui/avatar"
import { Label } from "@/components/drake_libs/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/drake_libs/ui/select"
import { Input } from "@/components/drake_libs/ui/input"
import { Textarea } from "@/components/drake_libs/ui/textarea"
import Link from "next/link"

export function Component() {
  return (
    <div className="flex flex-col h-full">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <ClapperboardIcon className="w-6 h-6" />
          <h1 className="text-2xl font-bold">Parent-Teacher Communication</h1>
        </div>
        <Button variant="ghost">
          <PlusIcon className="w-5 h-5" />
          <span className="sr-only">Create New Feedback</span>
        </Button>
      </header>
      <main className="flex-1 grid grid-cols-[300px_1fr] gap-6 p-6">
        <div className="bg-background rounded-lg shadow-md p-4">
          <h2 className="text-lg font-bold mb-4">My Students</h2>
          <div className="grid gap-2">
            <div className="flex items-center justify-between bg-muted rounded-md p-2">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Student 1" />
                  <AvatarFallback>S1</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Student 1</div>
                  <div className="text-xs text-muted-foreground">Grade 5</div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-green-500" />
                <span className="text-xs text-muted-foreground">Good</span>
              </div>
            </div>
            <div className="flex items-center justify-between bg-muted rounded-md p-2">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Student 2" />
                  <AvatarFallback>S2</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Student 2</div>
                  <div className="text-xs text-muted-foreground">Grade 5</div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500" />
                <span className="text-xs text-muted-foreground">Bad</span>
              </div>
            </div>
            <div className="flex items-center justify-between bg-muted rounded-md p-2">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" alt="Student 3" />
                  <AvatarFallback>S3</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Student 3</div>
                  <div className="text-xs text-muted-foreground">Grade 5</div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-green-500" />
                <span className="text-xs text-muted-foreground">Good</span>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-md p-4">
          <h2 className="text-lg font-bold mb-4">Feedback Composer</h2>
          <form className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="student">Student</Label>
              <Select id="student">
                <SelectTrigger>
                  <SelectValue placeholder="Select a student" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="student1">Student 1</SelectItem>
                  <SelectItem value="student2">Student 2</SelectItem>
                  <SelectItem value="student3">Student 3</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="grades">Grades</Label>
              <Input id="grades" placeholder="Enter student grades" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="behavior">Behavior</Label>
              <Textarea id="behavior" placeholder="Describe student behavior" />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="progress">Assignment Progress</Label>
              <Input id="progress" placeholder="Enter assignment progress" />
            </div>
            <Button type="submit">Send Feedback</Button>
          </form>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <CopyrightIcon className="w-4 h-4" />
          <span className="text-sm">2023 Parent-Teacher Communication</span>
        </div>
        <div className="flex items-center gap-4">
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Terms of Service
          </Link>
        </div>
      </footer>
    </div>
  )
}

function ClapperboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3Z" />
      <path d="m6.2 5.3 3.1 3.9" />
      <path d="m12.4 3.4 3.1 4" />
      <path d="M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" />
    </svg>
  )
}


function CopyrightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M14.83 14.83a4 4 0 1 1 0-5.66" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
