/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4ld4gwSC4W2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/drake_libs/ui/card"
import { Label } from "@/components/drake_libs/ui/label"
import { Input } from "@/components/drake_libs/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/drake_libs/ui/select"
import { Button } from "@/components/drake_libs/ui/button"

export function CreateStudentForm() {
  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="text-2xl font-bold">Student Registration</CardTitle>
        <CardDescription>Fill out the form to register a new student.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="firstName" className="font-medium">
              First Name <span className="text-red-500">*</span>
            </Label>
            <Input id="firstName" placeholder="Enter first name" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="lastName" className="font-medium">
              Last Name <span className="text-red-500">*</span>
            </Label>
            <Input id="lastName" placeholder="Enter last name" required />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="age" className="font-medium">
              Age <span className="text-red-500">*</span>
            </Label>
            <Input id="age" type="number" placeholder="Enter age" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="studentCode" className="font-medium">
              Student Code
            </Label>
            <Input id="studentCode" placeholder="Auto-generated" disabled />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="class" className="font-medium">
              Class
            </Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select class" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="grade-1">Grade 1</SelectItem>
                <SelectItem value="grade-2">Grade 2</SelectItem>
                <SelectItem value="grade-3">Grade 3</SelectItem>
                <SelectItem value="grade-4">Grade 4</SelectItem>
                <SelectItem value="grade-5">Grade 5</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="grade" className="font-medium">
              Grade
            </Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select grade" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="a">A</SelectItem>
                <SelectItem value="b">B</SelectItem>
                <SelectItem value="c">C</SelectItem>
                <SelectItem value="d">D</SelectItem>
                <SelectItem value="f">F</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button type="submit">Register</Button>
      </CardFooter>
    </Card>
  )
}
