/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x9tOraLBxwJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/drake_libs/ui/input"
import { Button } from "@/components/drake_libs/ui/button"
import { Card, CardHeader, CardTitle, CardContent, CardFooter, CardDescription } from "@/components/drake_libs/ui/card"
import { Checkbox } from "@/components/drake_libs/ui/checkbox"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/drake_libs/ui/select"
import { Switch } from "@/components/drake_libs/ui/switch"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/drake_libs/ui/tabs"

export function DashboardDrake() {
  return (
    <div className="flex min-h-screen">
      <aside className="w-64 bg-gray-800 text-white flex flex-col">
        <div className="flex items-center justify-center h-16 border-b border-gray-700">
          <span className="text-lg font-semibold">ABC Cleaning</span>
        </div>
        <nav className="flex-1 p-4 space-y-4">
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <HomeIcon className="w-6 h-6" />
            <span>Dashboard</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <UsersIcon className="w-6 h-6" />
            <span>Clients</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <TablePropertiesIcon className="w-6 h-6" />
            <span>Properties</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <WorkflowIcon className="w-6 h-6" />
            <span>Tasks</span>
          </Link>
          <Link href="#" className="flex items-center space-x-2" prefetch={false}>
            <FilesIcon className="w-6 h-6" />
            <span>Reports</span>
          </Link>
        </nav>
      </aside>
      <main className="flex-1 p-6 bg-gray-100">
        <header className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold">Client Details</h1>
          <div className="flex items-center space-x-4">
            <Input type="search" placeholder="Search" className="w-64" />
            <Button variant="outline">Back to Clients</Button>
          </div>
        </header>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Client Details</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 gap-4">
                <div className="grid grid-cols-3 gap-4">
                  <Input placeholder="Title" />
                  <Input placeholder="First name" defaultValue="Natasha" />
                  <Input placeholder="Last name" defaultValue="Wheeler" />
                </div>
                <Input placeholder="Company name" />
                <div className="flex items-center space-x-2">
                  <Checkbox id="use-company-name" />
                  <label htmlFor="use-company-name" className="text-sm">
                    Use company name as primary name
                  </label>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="Main" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="main">Main</SelectItem>
                      <SelectItem value="secondary">Secondary</SelectItem>
                    </SelectContent>
                  </Select>
                  <Input placeholder="Phone number" />
                </div>
                <div className="flex items-center space-x-2">
                  <Switch id="receives-texts" defaultChecked />
                  <label htmlFor="receives-texts" className="text-sm">
                    Receives text messages
                  </label>
                </div>
                <Button variant="link" className="text-green-500">
                  Add phone number
                </Button>
                <div className="grid grid-cols-2 gap-4">
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="Main" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="main">Main</SelectItem>
                      <SelectItem value="secondary">Secondary</SelectItem>
                    </SelectContent>
                  </Select>
                  <Input placeholder="Email address" />
                </div>
                <Button variant="link" className="text-green-500">
                  Add Email Address
                </Button>
                <div className="space-y-2">
                  <Button variant="outline" className="w-full">
                    Automated notifications
                  </Button>
                  <Button variant="outline" className="w-full">
                    Additional client details
                  </Button>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex justify-end">
              <Button variant="outline">Cancel</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Property Details</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 gap-4">
                <Input placeholder="Street 1" />
                <Input placeholder="Street 2" />
                <Input placeholder="City" />
                <Input placeholder="Postal code" />
                <div className="flex items-center space-x-2">
                  <Checkbox id="billing-address" />
                  <label htmlFor="billing-address" className="text-sm">
                    Billing address is the same as property address
                  </label>
                </div>
                <Button variant="outline" className="w-full">
                  Additional property details
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <div className="fixed bottom-0 right-0 w-full md:hidden">
        <Card className="rounded-t-lg">
          <CardHeader className="flex items-center justify-between">
            <div>
              <CardTitle>Robin Schneider</CardTitle>
              <CardDescription>Client balance: $1,581.38</CardDescription>
            </div>
            <Button variant="outline" className="flex items-center">
              <PhoneIcon className="w-4 h-4" />
              <MailIcon className="w-4 h-4 ml-2" />
            </Button>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="client">
              <TabsList className="flex space-x-4">
                <TabsTrigger value="client">Client</TabsTrigger>
                <TabsTrigger value="work">Work</TabsTrigger>
                <TabsTrigger value="notes">Notes</TabsTrigger>
              </TabsList>
              <TabsContent value="client">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-medium">Properties</h2>
                    <Button variant="link" className="text-green-500">
                      <PlusIcon className="w-4 h-4" />
                    </Button>
                  </div>
                  <div className="space-y-2">
                    <div className="p-4 border rounded-md">
                      <p>10303 Jasper Avenue</p>
                      <p>Edmonton, Alberta T5J 4H8</p>
                      <p>Tax rate: 7%</p>
                      <p>Locked Gate: No</p>
                      <p>Dog: No</p>
                      <p>Lawn Size: -</p>
                      <p>Gate Code: -</p>
                    </div>
                  </div>
                </div>
              </TabsContent>
              <TabsContent value="work">
                <p>Work details will be displayed here.</p>
              </TabsContent>
              <TabsContent value="notes">
                <p>Notes will be displayed here.</p>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function FilesIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 7h-3a2 2 0 0 1-2-2V2" />
      <path d="M9 18a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h7l4 4v10a2 2 0 0 1-2 2Z" />
      <path d="M3 7.6v12.8A1.6 1.6 0 0 0 4.6 22h9.8" />
    </svg>
  )
}


function HomeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TablePropertiesIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3v18" />
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M21 9H3" />
      <path d="M21 15H3" />
    </svg>
  )
}


function UsersIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function WorkflowIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  )
}
