/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BRuXxPQpMpp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/drake_libs/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/drake_libs/ui/card"
import { Progress } from "@/components/drake_libs/ui/progress"

export default function Example() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background">
      <header className="bg-card py-4 px-6 border-b">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">Parent Dashboard</h1>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon">
              <SettingsIcon className="w-6 h-6 text-muted-foreground" />
            </Button>
            <img
              src="/placeholder.svg"
              width={40}
              height={40}
              className="rounded-full"
              alt="User avatar"
              style={{ aspectRatio: "40/40", objectFit: "cover" }}
            />
          </div>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-6">
        <section className="col-span-1 lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>Teacher Feedback</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="grid gap-4">
                <Card className="bg-green-100 border-green-500">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="font-bold">Ms. Johnson</div>
                      <div className="text-sm text-muted-foreground">May 15, 2024</div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p>
                      Your child has been doing an excellent job in class. They are engaged, attentive, and consistently
                      completing their assignments on time.
                    </p>
                  </CardContent>
                </Card>
                <Card className="bg-red-100 border-red-500">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="font-bold">Mr. Lee</div>
                      <div className="text-sm text-muted-foreground">April 30, 2024</div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p>
                      I have some concerns about your child's behavior in class. They have been disruptive and not
                      completing their assignments on time. Please let's schedule a meeting to discuss this further.
                    </p>
                  </CardContent>
                </Card>
                <Card className="bg-green-100 border-green-500">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div className="font-bold">Ms. Patel</div>
                      <div className="text-sm text-muted-foreground">March 20, 2024</div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p>
                      Your child has been doing an amazing job in my class. They are always prepared, ask thoughtful
                      questions, and contribute positively to class discussions.
                    </p>
                  </CardContent>
                </Card>
              </div>
            </CardContent>
          </Card>
        </section>
        <section className="col-span-1 lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Student Performance</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Grades</div>
                  <div className="text-primary font-bold">A-</div>
                </div>
                <Progress value={85} />
              </div>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Behavior</div>
                  <div className="text-primary font-bold">Excellent</div>
                </div>
                <Progress value={90} />
              </div>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Assignments</div>
                  <div className="text-primary font-bold">92%</div>
                </div>
                <Progress value={92} />
              </div>
            </CardContent>
          </Card>
        </section>
        <section className="col-span-1 lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Feedback Templates</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4">
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Positive Feedback</div>
                  <Button size="sm">Edit</Button>
                </div>
                <p className="text-sm text-muted-foreground">
                  Your child has been doing an excellent job in my class. They are engaged, attentive, and consistently
                  completing their assignments on time.
                </p>
              </div>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Negative Feedback</div>
                  <Button size="sm">Edit</Button>
                </div>
                <p className="text-sm text-muted-foreground">
                  I have some concerns about your child's behavior in class. They have been disruptive and not
                  completing their assignments on time. Please let's schedule a meeting to discuss this further.
                </p>
              </div>
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  )
}

function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
