/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U7bn14rVBIR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function LearningMaterialV2() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BookOpenIcon className="h-6 w-6" />
          <span className="sr-only">English Learning Center</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Lessons
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Explore Our Learning Materials</h2>
              <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Browse through our comprehensive collection of English lessons, covering a wide range of topics to help
                you improve your language skills.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-8">
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Grammar Lessons"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Grammar Lessons</h3>
                  <p className="text-sm text-muted-foreground">
                    Improve your grammar skills with our comprehensive lessons.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Vocabulary Building"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Vocabulary Building</h3>
                  <p className="text-sm text-muted-foreground">Expand your vocabulary with our engaging lessons.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Conversation Practice"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Conversation Practice</h3>
                  <p className="text-sm text-muted-foreground">
                    Improve your speaking skills with our conversation lessons.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Pronunciation Mastery"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Pronunciation Mastery</h3>
                  <p className="text-sm text-muted-foreground">
                    Perfect your English pronunciation with our specialized lessons.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Idioms and Expressions"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Idioms and Expressions</h3>
                  <p className="text-sm text-muted-foreground">Learn the most common English idioms and expressions.</p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Business English"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Business English</h3>
                  <p className="text-sm text-muted-foreground">
                    Develop your professional English skills for the workplace.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Listening Comprehension"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Listening Comprehension</h3>
                  <p className="text-sm text-muted-foreground">
                    Improve your listening skills with our interactive lessons.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group relative overflow-hidden rounded-lg shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Writing Essentials"
                  width="300"
                  height="200"
                  className="object-cover w-full h-48"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div className="p-4 bg-background">
                  <h3 className="text-lg font-bold">Writing Essentials</h3>
                  <p className="text-sm text-muted-foreground">
                    Develop your English writing skills with our structured lessons.
                  </p>
                </div>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">About</h3>
            <Link href="#" prefetch={false}>
              Our Mission
            </Link>
            <Link href="#" prefetch={false}>
              Our Team
            </Link>
            <Link href="#" prefetch={false}>
              Careers
            </Link>
            <Link href="#" prefetch={false}>
              Blog
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Lessons</h3>
            <Link href="#" prefetch={false}>
              Grammar
            </Link>
            <Link href="#" prefetch={false}>
              Vocabulary
            </Link>
            <Link href="#" prefetch={false}>
              Conversation
            </Link>
            <Link href="#" prefetch={false}>
              Pronunciation
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Worksheets
            </Link>
            <Link href="#" prefetch={false}>
              Practice Tests
            </Link>
            <Link href="#" prefetch={false}>
              Study Guides
            </Link>
            <Link href="#" prefetch={false}>
              FAQs
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
            <Link href="#" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" prefetch={false}>
              Cookie Policy
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Contact</h3>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              Inquiries
            </Link>
            <Link href="#" prefetch={false}>
              Partnerships
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function BookOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}
