/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/joKuq2Cq858
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/drake_libs/ui/button"
import { Card, CardContent } from "@/components/drake_libs/ui/card"
import { Badge } from "@/components/drake_libs/ui/badge"

export function StudentManagements() {
  return (
    <div className="max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Student Management</h1>
        <Button className="flex items-center gap-2">
          <PlusIcon className="w-4 h-4" />
          Add Student
        </Button>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <Card>
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold">John Doe</h2>
                <div className="flex items-center gap-2">
                  <Badge>Grade 10</Badge>
                  <Badge variant="secondary">Math</Badge>
                </div>
              </div>
              <div className="text-muted-foreground">
                <div>Class: Math</div>
                <div>Grade: A</div>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <Button variant="outline" size="sm">
                <EyeIcon className="w-4 h-4" />
                View
              </Button>
              <Button variant="outline" size="sm">
                <FilePenIcon className="w-4 h-4" />
                Edit
              </Button>
              <Button variant="outline" size="sm">
                <TrashIcon className="w-4 h-4" />
                Delete
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold">Jane Smith</h2>
                <div className="flex items-center gap-2">
                  <Badge>Grade 11</Badge>
                  <Badge variant="secondary">English</Badge>
                </div>
              </div>
              <div className="text-muted-foreground">
                <div>Class: English</div>
                <div>Grade: B+</div>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <Button variant="outline" size="sm">
                <EyeIcon className="w-4 h-4" />
                View
              </Button>
              <Button variant="outline" size="sm">
                <FilePenIcon className="w-4 h-4" />
                Edit
              </Button>
              <Button variant="outline" size="sm">
                <TrashIcon className="w-4 h-4" />
                Delete
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold">Michael Johnson</h2>
                <div className="flex items-center gap-2">
                  <Badge>Grade 9</Badge>
                  <Badge variant="secondary">Science</Badge>
                </div>
              </div>
              <div className="text-muted-foreground">
                <div>Class: Science</div>
                <div>Grade: B</div>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <Button variant="outline" size="sm">
                <EyeIcon className="w-4 h-4" />
                View
              </Button>
              <Button variant="outline" size="sm">
                <FilePenIcon className="w-4 h-4" />
                Edit
              </Button>
              <Button variant="outline" size="sm">
                <TrashIcon className="w-4 h-4" />
                Delete
              </Button>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-2">
                <h2 className="text-lg font-semibold">Emily Davis</h2>
                <div className="flex items-center gap-2">
                  <Badge>Grade 12</Badge>
                  <Badge variant="secondary">History</Badge>
                </div>
              </div>
              <div className="text-muted-foreground">
                <div>Class: History</div>
                <div>Grade: A-</div>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <Button variant="outline" size="sm">
                <EyeIcon className="w-4 h-4" />
                View
              </Button>
              <Button variant="outline" size="sm">
                <FilePenIcon className="w-4 h-4" />
                Edit
              </Button>
              <Button variant="outline" size="sm">
                <TrashIcon className="w-4 h-4" />
                Delete
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function EyeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function FilePenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
