/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QDQYWothN0a
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function StudentDetail() {
  return (
    <div className="max-w-md mx-auto p-6 bg-background rounded-lg shadow-md">
      <div className="flex items-center space-x-4">
        <div className="bg-primary rounded-full w-16 h-16 flex items-center justify-center text-primary-foreground text-2xl font-bold">
          JD
        </div>
        <div>
          <h1 className="text-2xl font-bold">John Doe</h1>
          <div className="text-muted-foreground">Grade: 10 | Class: 10A | Age: 15</div>
        </div>
      </div>
      <div className="mt-6 space-y-4">
        <div>
          <h2 className="text-lg font-semibold">About</h2>
          <p className="text-muted-foreground">
            John is a hardworking and dedicated student who always strives to do his best. He is passionate about
            science and enjoys participating in extracurricular activities.
          </p>
        </div>
        <div>
          <h2 className="text-lg font-semibold">Academic Performance</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="text-muted-foreground">GPA</div>
              <div className="text-2xl font-bold">3.8</div>
            </div>
            <div>
              <div className="text-muted-foreground">Attendance</div>
              <div className="text-2xl font-bold">95%</div>
            </div>
          </div>
        </div>
        <div>
          <h2 className="text-lg font-semibold">Extracurricular Activities</h2>
          <ul className="space-y-2">
            <li>
              <div className="flex items-center space-x-2">
                <div className="bg-primary rounded-full w-8 h-8 flex items-center justify-center text-primary-foreground">
                  🏀
                </div>
                <div>Basketball Club</div>
              </div>
            </li>
            <li>
              <div className="flex items-center space-x-2">
                <div className="bg-primary rounded-full w-8 h-8 flex items-center justify-center text-primary-foreground">
                  🎨
                </div>
                <div>Art Club</div>
              </div>
            </li>
            <li>
              <div className="flex items-center space-x-2">
                <div className="bg-primary rounded-full w-8 h-8 flex items-center justify-center text-primary-foreground">
                  🤖
                </div>
                <div>Robotics Club</div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  )
}
