
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UyFlz6Y6lbw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import { Input } from "@/components/drake_libs/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem } from "@/components/drake_libs/ui/dropdown-menu"
import { Button } from "@/components/drake_libs/ui/button"
import { Card } from "@/components/drake_libs/ui/card"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/drake_libs/ui/table"

export default function ActivityLog() {
  const [search, setSearch] = useState("")
  const [filter, setFilter] = useState({
    type: "all",
    user: "all",
  })
  const activities = useMemo(
    () => [
      {
        id: 1,
        type: "Login",
        timestamp: "2023-08-24 10:15 AM",
        user: "john@example.com",
        details: "Logged in from a new device",
      },
      {
        id: 2,
        type: "File Upload",
        timestamp: "2023-08-23 3:30 PM",
        user: "jane@example.com",
        details: "Uploaded a new design file",
      },
      {
        id: 3,
        type: "Payment",
        timestamp: "2023-08-22 9:00 AM",
        user: "bob@example.com",
        details: "Completed a payment of $99.99",
      },
      {
        id: 4,
        type: "Login",
        timestamp: "2023-08-21 11:45 AM",
        user: "alice@example.com",
        details: "Logged in from a new location",
      },
      {
        id: 5,
        type: "File Download",
        timestamp: "2023-08-20 2:00 PM",
        user: "john@example.com",
        details: "Downloaded a report file",
      },
      {
        id: 6,
        type: "Payment",
        timestamp: "2023-08-19 4:30 PM",
        user: "jane@example.com",
        details: "Completed a payment of $49.99",
      },
    ],
    [],
  )
  const filteredActivities = useMemo(() => {
    return activities.filter((activity) => {
      if (filter.type !== "all" && activity.type !== filter.type) {
        return false
      }
      if (filter.user !== "all" && activity.user !== filter.user) {
        return false
      }
      return (
        activity.type.toLowerCase().includes(search.toLowerCase()) ||
        activity.user.toLowerCase().includes(search.toLowerCase()) ||
        activity.details.toLowerCase().includes(search.toLowerCase())
      )
    })
  }, [activities, search, filter])
  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Activity Log</h1>
        <div className="flex items-center gap-4">
          <div className="relative">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search activities..."
              className="pl-8 w-[300px]"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm">
                <FilterIcon className="h-4 w-4 mr-2" />
                Filter
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Filter by</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem
                checked={filter.type === "all"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, type: "all" }))}
              >
                All
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.type === "Login"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, type: "Login" }))}
              >
                Login
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.type === "File Upload"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, type: "File Upload" }))}
              >
                File Upload
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.type === "Payment"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, type: "Payment" }))}
              >
                Payment
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.type === "File Download"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, type: "File Download" }))}
              >
                File Download
              </DropdownMenuCheckboxItem>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem
                checked={filter.user === "all"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, user: "all" }))}
              >
                All Users
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.user === "john@example.com"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, user: "john@example.com" }))}
              >
                John
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.user === "jane@example.com"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, user: "jane@example.com" }))}
              >
                Jane
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.user === "bob@example.com"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, user: "bob@example.com" }))}
              >
                Bob
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem
                checked={filter.user === "alice@example.com"}
                onCheckedChange={() => setFilter((prev) => ({ ...prev, user: "alice@example.com" }))}
              >
                Alice
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <Card className="overflow-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Activity</TableHead>
              <TableHead>Timestamp</TableHead>
              <TableHead>User</TableHead>
              <TableHead>Details</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredActivities.map((activity) => (
              <TableRow key={activity.id}>
                <TableCell>{activity.type}</TableCell>
                <TableCell>{activity.timestamp}</TableCell>
                <TableCell>{activity.user}</TableCell>
                <TableCell>{activity.details}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  )
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
